# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from confirma import Ui_MainWindow

class Ui_Form(object):

    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        self.window.show()

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(340, 282)
        self.Cadastrar = QtWidgets.QPushButton(Form)
        self.Cadastrar.setGeometry(QtCore.QRect(130, 200, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Cadastrar.clicked.connect(self.openWindow)
        self.Cadastrar.setFont(font)
        self.Cadastrar.setMouseTracking(False)
        self.Cadastrar.setDefault(True)
        self.Cadastrar.setObjectName("Cadastrar")
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setGeometry(QtCore.QRect(150, 50, 161, 31))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 60, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        self.Cadastrar.clicked.connect(self.textEdit.showNormal) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Cadastrar.setText(_translate("Form", "Cadastrar"))
        self.label.setText(_translate("Form", "Nome Usuário"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
